apiVersion: v1
kind: Service
metadata:
  name: dummy-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: dummy-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 8080